"""
chat_app.py  –  A ChatGPT-style chat interface built with Streamlit.
No external LLMs or APIs are used. All responses are generated locally
by a small Python function using keyword matching and randomised replies.

Run with:  streamlit run chat_app.py
"""

import random
import streamlit as st

# ─────────────────────────────────────────────
# Page configuration
# ─────────────────────────────────────────────
st.set_page_config(
    page_title="MockChat",
    page_icon="💬",
    layout="centered",
)

# ─────────────────────────────────────────────
# Custom CSS for a polished look
# ─────────────────────────────────────────────
st.markdown(
    """
    <style>
    @import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;600&family=IBM+Plex+Sans:wght@300;400;600&display=swap');

    html, body, [class*="css"] {
        font-family: 'IBM Plex Sans', sans-serif;
    }

    /* App background */
    .stApp {
        background: #0d0f14;
        color: #e8eaf0;
    }

    /* Hide default Streamlit header / footer */
    header[data-testid="stHeader"] { display: none; }
    footer { display: none; }

    /* Title banner */
    .title-block {
        text-align: center;
        padding: 2rem 0 1rem;
    }
    .title-block h1 {
        font-family: 'IBM Plex Mono', monospace;
        font-size: 2.4rem;
        font-weight: 600;
        letter-spacing: -1px;
        color: #f0f2f8;
        margin: 0;
    }
    .title-block p {
        font-size: 0.85rem;
        color: #6b7280;
        margin-top: 0.3rem;
        font-family: 'IBM Plex Mono', monospace;
    }

    /* Chat messages */
    [data-testid="stChatMessage"] {
        background: #151820 !important;
        border: 1px solid #1e2230 !important;
        border-radius: 12px !important;
        padding: 1rem 1.2rem !important;
        margin-bottom: 0.6rem !important;
    }

    /* User message accent */
    [data-testid="stChatMessage"]:has([data-testid="chatAvatarIcon-user"]) {
        border-left: 3px solid #6366f1 !important;
    }

    /* Assistant message accent */
    [data-testid="stChatMessage"]:has([data-testid="chatAvatarIcon-assistant"]) {
        border-left: 3px solid #22d3ee !important;
    }

    /* Chat input */
    [data-testid="stChatInput"] > div {
        background: #151820 !important;
        border: 1px solid #2a2f40 !important;
        border-radius: 12px !important;
        color: #e8eaf0 !important;
    }
    [data-testid="stChatInput"] textarea {
        color: #e8eaf0 !important;
        font-family: 'IBM Plex Sans', sans-serif !important;
    }

    /* Sidebar */
    [data-testid="stSidebar"] {
        background: #101318 !important;
        border-right: 1px solid #1e2230 !important;
    }
    </style>
    """,
    unsafe_allow_html=True,
)

# ─────────────────────────────────────────────
# Title
# ─────────────────────────────────────────────
st.markdown(
    """
    <div class="title-block">
        <h1>💬 MockChat</h1>
        <p>local · no API · no LLM · 100% Python</p>
    </div>
    """,
    unsafe_allow_html=True,
)

# ─────────────────────────────────────────────
# Session-state: persist conversation history
# ─────────────────────────────────────────────
if "messages" not in st.session_state:
    st.session_state.messages = [
        {
            "role": "assistant",
            "content": (
                "Hey there! 👋 I'm **MockChat**, a local demo assistant "
                "running entirely in Python — no API key needed. "
                "Ask me anything (I'll do my best with keywords 😄)."
            ),
        }
    ]

# ─────────────────────────────────────────────
# Sidebar – controls
# ─────────────────────────────────────────────
with st.sidebar:
    st.markdown("### ⚙️ Controls")
    if st.button("🗑️ Clear conversation", use_container_width=True):
        st.session_state.messages = [
            {
                "role": "assistant",
                "content": "Conversation cleared. Fresh start! What's on your mind?",
            }
        ]
    st.markdown("---")
    st.markdown(
        """
        **Tech stack**
        - Python 3.x
        - Streamlit ≥ 1.32
        - `st.chat_message`
        - `st.chat_input`
        - `st.session_state`

        **How it works**  
        Responses are generated by a local keyword-matching function — zero external calls.
        """
    )

# ─────────────────────────────────────────────
# Local mock-response engine (no LLM / no API)
# ─────────────────────────────────────────────
RESPONSES: dict[str, list[str]] = {
    # Greetings
    ("hello", "hi", "hey", "howdy", "greetings"): [
        "Hello! How can I help you today?",
        "Hey! Great to hear from you. What's up?",
        "Hi there! Ask me anything — I'll do my best.",
    ],
    # Farewell
    ("bye", "goodbye", "see you", "ciao", "later"): [
        "Goodbye! Have a wonderful day 👋",
        "See you later! Take care.",
        "Bye! Come back anytime.",
    ],
    # How are you
    ("how are you", "how's it going", "how do you do", "you ok"): [
        "I'm just a bunch of `if` statements, but I feel great! 😄",
        "Running smoothly on your machine — no cloud required!",
        "Doing well, thanks for asking. How about you?",
    ],
    # Name
    ("your name", "who are you", "what are you"): [
        "I'm **MockChat** — a local Streamlit demo with zero external APIs.",
        "Call me MockChat! Built purely in Python for this demo.",
    ],
    # Python
    ("python", "code", "programming", "script"): [
        "Python is fantastic! This whole app is under 200 lines of it.",
        "Love Python! Streamlit makes building chat UIs incredibly simple.",
        "Clean code beats clever code every time. What would you like to build?",
    ],
    # Streamlit
    ("streamlit",): [
        "`st.chat_message` and `st.chat_input` make chat UIs trivial to build.",
        "Streamlit turns a Python script into a web app in minutes — magic!",
        "Check out https://docs.streamlit.io for the full docs.",
    ],
    # Weather
    ("weather", "rain", "sunny", "temperature", "forecast"): [
        "I can't check live weather (no internet!), but I hope it's sunny where you are ☀️",
        "No API key means no live weather — sorry! Try weather.com.",
    ],
    # Joke
    ("joke", "funny", "laugh", "humor"): [
        "Why do Python developers prefer dark mode? Because light attracts bugs! 🐛",
        "I told my computer I needed a break. Now it won't stop sending me Kit-Kat ads.",
        "A SQL query walks into a bar, walks up to two tables and asks… 'Can I join you?'",
    ],
    # Time / date
    ("time", "date", "today", "day"): [
        "I don't have a live clock, but Python's `datetime.now()` would tell you!",
        "Check your system clock — I'm running offline 😄",
    ],
    # Thank you
    ("thank", "thanks", "appreciate", "cheers"): [
        "You're very welcome! 😊",
        "Happy to help — anytime!",
        "My pleasure! Anything else?",
    ],
    # Help
    ("help", "what can you do", "capabilities"): [
        (
            "I can chat, tell jokes, talk about Python & Streamlit, "
            "and give general replies — all locally, no API needed!"
        ),
        "Try asking about Python, Streamlit, jokes, or just say hello!",
    ],
}

FALLBACK_RESPONSES: list[str] = [
    "Interesting! Tell me more.",
    "I'm a simple keyword bot, so I might miss nuance — but I'm listening!",
    "Hmm, I'm not sure how to respond to that. Try asking about Python or Streamlit!",
    "Great question! Unfortunately my local logic doesn't cover that one yet.",
    "I'll have to pass on that — my knowledge is hard-coded 😄 Ask me something else!",
]


def generate_response(user_input: str) -> str:
    """
    Pure-Python mock response generator.

    Steps:
    1. Normalise the input to lowercase.
    2. Iterate over keyword groups; if any keyword appears in the input,
       return a random reply from that group.
    3. If nothing matches, return a random fallback reply.

    No external network calls, no LLM, no API key required.
    """
    text = user_input.lower().strip()

    for keywords, replies in RESPONSES.items():
        if any(kw in text for kw in keywords):
            return random.choice(replies)

    return random.choice(FALLBACK_RESPONSES)


# ─────────────────────────────────────────────
# Render existing conversation history
# ─────────────────────────────────────────────
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])

# ─────────────────────────────────────────────
# Handle new user input
# ─────────────────────────────────────────────
if user_input := st.chat_input("Type a message…"):
    # 1. Store & display user message
    st.session_state.messages.append({"role": "user", "content": user_input})
    with st.chat_message("user"):
        st.markdown(user_input)

    # 2. Generate local mock reply
    reply = generate_response(user_input)

    # 3. Store & display assistant reply
    st.session_state.messages.append({"role": "assistant", "content": reply})
    with st.chat_message("assistant"):
        st.markdown(reply)